package net.zartra.gui;
import java.lang.reflect.*;import java.util.*;import java.io.File;import java.util.logging.Logger;import org.bukkit.inventory.ItemStack;import org.bukkit.*;import org.bukkit.entity.Player;import org.bukkit.plugin.PluginManager;import org.bukkit.scheduler.BukkitScheduler;import org.junit.*;import static org.junit.Assert.*;
public class ActionExecutorRuntimeTest {private static ActionExecutorRuntimeTest current;private final List<String> messages=new ArrayList<String>();private final List<Long> delays=new ArrayList<Long>();private boolean op;
 @BeforeClass public static void installServer(){Bukkit.setServer((Server)Proxy.newProxyInstance(ActionExecutorRuntimeTest.class.getClassLoader(),new Class[]{Server.class},new InvocationHandler(){public Object invoke(Object p,Method m,Object[] a){String n=m.getName();if("getLogger".equals(n))return java.util.logging.Logger.getLogger("test");if("getServerName".equals(n))return "unit";if("getOnlinePlayers".equals(n))return Collections.emptyList();if("getMaxPlayers".equals(n))return 20;if("getPluginManager".equals(n))return pluginManager();if("getScheduler".equals(n))return scheduler();return fallback(m.getReturnType());}}));}
 @Before public void reset(){current=this;messages.clear();delays.clear();op=false;} @Test public void dispatcherRunsStoredOrderAcrossDelayAndWait(){ActionEntry one=message("one"),wait=entry("WAIT","3"),two=message("two");one.delay=2;List<ActionEntry> actions=Arrays.asList(one,wait,two);new ActionExecutor(null,null).run(player(),new MenuDefinition("unit","Unit",3),actions);assertEquals(Arrays.asList("one","two"),messages);assertEquals(Arrays.asList(2L,3L),delays);}
 @Test public void acceptancePersistenceReloadThenDispatchesInStoredOrder()throws Exception{File dir=new File(System.getProperty("java.io.tmpdir"),"zgui-accept-"+System.nanoTime());MenuStorage storage=new MenuStorage(dir,Logger.getLogger("test"));MenuDefinition made=new MenuDefinition("accept","Accept",3);MenuItem item=new MenuItem(new ItemStack(Material.STONE),null);ActionEntry second=message("second");second.order=1;ActionEntry first=message("first");first.order=0;item.actions(MenuClickType.LEFT).add(second);item.actions(MenuClickType.LEFT).add(first);made.items.put(0,item);storage.save(made);MenuDefinition reopened=storage.load().get("accept");new ActionExecutor(null,null).run(player(),reopened,reopened.items.get(0).actions(MenuClickType.LEFT));assertEquals(Arrays.asList("first","second"),messages);}
 @Test public void disabledAndFailedStopBehaviorAreApplied(){ActionEntry off=message("off");off.enabled=false;ActionEntry bad=entry("WAIT","bad");bad.stopOnFailure=true;ActionEntry after=message("after");new ActionExecutor(null,null).run(player(),new MenuDefinition("unit","Unit",3),Arrays.asList(off,bad,after));assertTrue(messages.isEmpty());}
 @Test public void opIsRestoredAndPlaceholdersAreExpanded(){ActionEntry a=entry("OP_COMMAND","say %player% %menu_id% %server%");new ActionExecutor(null,null).run(player(),new MenuDefinition("unit","Unit",3),Collections.singletonList(a));assertFalse(op);assertEquals(Arrays.asList("cmd:say Alex unit unit"),messages);}
 private ActionEntry message(String s){return entry("MESSAGE",s);}private ActionEntry entry(String t,String v){ActionEntry a=new ActionEntry();a.type=t;a.value=v;return a;}
 private Player player(){return (Player)Proxy.newProxyInstance(ActionExecutorRuntimeTest.class.getClassLoader(),new Class[]{Player.class},new InvocationHandler(){public Object invoke(Object p,Method m,Object[] a){String n=m.getName();if("isOnline".equals(n))return true;if("getName".equals(n)||"getDisplayName".equals(n))return "Alex";if("getUniqueId".equals(n))return new UUID(0,1);if("sendMessage".equals(n)){messages.add(String.valueOf(a[0]));return null;}if("isOp".equals(n))return op;if("setOp".equals(n)){op=(Boolean)a[0];return null;}if("performCommand".equals(n)){messages.add("cmd:"+a[0]);return true;}if("getWorld".equals(n))return world();if("getLocation".equals(n))return new Location(world(),0,0,0);if("getGameMode".equals(n))return GameMode.SURVIVAL;if("getLevel".equals(n)||"getFoodLevel".equals(n))return 0;if("getHealth".equals(n)||"getMaxHealth".equals(n))return 20D;return fallback(m.getReturnType());}});}
 private World world(){return (World)Proxy.newProxyInstance(ActionExecutorRuntimeTest.class.getClassLoader(),new Class[]{World.class},new InvocationHandler(){public Object invoke(Object p,Method m,Object[] a){return "getName".equals(m.getName())?"world":fallback(m.getReturnType());}});}
 private static PluginManager pluginManager(){return (PluginManager)Proxy.newProxyInstance(ActionExecutorRuntimeTest.class.getClassLoader(),new Class[]{PluginManager.class},new InvocationHandler(){public Object invoke(Object p,Method m,Object[] a){return fallback(m.getReturnType());}});}
 private static BukkitScheduler scheduler(){return (BukkitScheduler)Proxy.newProxyInstance(ActionExecutorRuntimeTest.class.getClassLoader(),new Class[]{BukkitScheduler.class},new InvocationHandler(){public Object invoke(Object p,Method m,Object[] a){if("runTaskLater".equals(m.getName())){current.delays.add((Long)a[2]);((Runnable)a[1]).run();}return fallback(m.getReturnType());}});}
 private static Object fallback(Class<?> c){if(c==Boolean.TYPE)return false;if(c==Integer.TYPE)return 0;if(c==Long.TYPE)return 0L;if(c==Double.TYPE)return 0D;if(c==Float.TYPE)return 0F;return null;}
}