package net.zartra.gui;
import static org.junit.Assert.*;import java.nio.charset.Charset;import java.nio.file.*;import org.junit.Test;
public class ChatColorPickerTest {
 @Test public void hueSpectrumCoversPrimaryRange(){int[][] h=ChatColorPalette.hues();assertEquals(30,h.length);assertArrayEquals(new int[]{255,0,0},h[0]);assertTrue(h[5][1]>200);assertTrue(h[10][1]>200);assertTrue(h[15][1]>200&&h[15][2]>200);assertTrue(h[20][2]>200);}
 @Test public void shadeGridContainsPaleVividDarkAndGrayscale(){int[][] s=ChatColorPalette.shades(0);assertEquals(64,s.length);assertArrayEquals(new int[]{255,255,255},s[0]);assertTrue(s[7][0]>200&&s[7][1]<10);assertArrayEquals(new int[]{46,46,46},s[56]);}
 @Test public void hsvAndHexAreDeterministic(){assertArrayEquals(new int[]{0,255,0},ChatColorPalette.hsv(120,1,1));assertArrayEquals(new int[]{0,0,255},ChatColorPalette.hsv(240,1,1));assertEquals("#00FF0A",ChatColorPalette.hex(new int[]{0,255,10}));assertEquals("#FF0000",ChatColorPalette.hex(new int[]{999,-2,0}));}
 @Test public void legacyMappingIsStable(){assertEquals("4",ChatColorPalette.legacy(new int[]{255,0,0}));assertEquals("9",ChatColorPalette.legacy(new int[]{40,80,255}));assertEquals("0",ChatColorPalette.legacy(new int[]{0,0,0}));}
 @Test public void pickerUsesOpaqueTokensAndConstrainedActions()throws Exception{String s=new String(Files.readAllBytes(Paths.get("src/main/java/net/zartra/gui/ChatColorPicker.java")),Charset.forName("UTF-8"));assertTrue(s.contains("SecureRandom"));assertTrue(s.contains("sessions.get(token)"));assertTrue(s.contains("s.player.equals(p.getUniqueId())"));assertTrue(s.contains("expires"));assertTrue(s.contains("_zgui_picker"));}
 @Test public void componentBridgeHasNoDirectBungeeImports()throws Exception{String s=new String(Files.readAllBytes(Paths.get("src/main/java/net/zartra/gui/ChatComponentCompat.java")),Charset.forName("UTF-8"));assertTrue(s.contains("Class.forName"));assertTrue(s.contains("Approximate legacy preview"));assertFalse(s.contains("import net.md_5"));}
 @Test public void existingPickerKeepsInventoryControlsAndAddsChatRoute()throws Exception{String s=new String(Files.readAllBytes(Paths.get("src/main/java/net/zartra/gui/GuiService.java")),Charset.forName("UTF-8"));assertTrue(s.contains("Chat Color Picker"));assertTrue(s.contains("openChatLeatherPicker"));assertTrue(s.contains("applyLeatherColor"));assertTrue(s.contains("checkpoint(p,d)"));}
}