package net.zartra.gui;
import java.nio.charset.Charset;import java.nio.file.*;import org.junit.Test;import static org.junit.Assert.*;
public class CommandModalRegressionTest {
 private String source(String n)throws Exception{return new String(Files.readAllBytes(Paths.get("src/main/java/net/zartra/gui/"+n)),Charset.forName("UTF-8"));}
 @Test public void allAliasesHaveDescriptorSupport()throws Exception{String y=new String(Files.readAllBytes(Paths.get("src/main/resources/plugin.yml")),Charset.forName("UTF-8"));assertTrue(y.contains("aliases: [zartragui, guimaker, gui]"));}
 @Test public void openAndPreviewHaveExplicitPlayerMenuRouting()throws Exception{String s=source("ZGuiCommand.java");assertTrue(s.contains("if(\"open\".equals(sub))"));assertTrue(s.contains("if(\"preview\".equals(sub))"));assertTrue(s.contains("requiredMenu(s,sub,a)"));assertTrue(s.contains("playerOnly(s)"));assertTrue(s.contains("menus.open((Player)s,d)"));assertTrue(s.contains("menus.openPreview((Player)s,d)"));assertTrue(s.contains("Unknown menu:"));assertTrue(s.contains("Usage: /zgui "+"\"+sub+\" <menu-id>"));}
 @Test public void previewIsSeparateAndCannotRunRuntimeActions()throws Exception{String m=source("MenuManager.java"),l=source("GuiListener.java"),g=source("GuiService.java");assertTrue(m.contains("void openPreview"));assertTrue(m.contains("Screen.PREVIEW"));assertFalse(m.substring(m.indexOf("void openPreview"),m.indexOf("private void open")).contains("actions.run"));assertTrue(l.contains("h.screen!=MenuManager.Screen.NONE"));assertTrue(g.contains("menus.openPreview(p,d)"));}
 @Test public void modalPromptFollowsIntentionalClose()throws Exception{String i=source("ChatInputManager.java"),g=source("GuiService.java");assertFalse(i.contains("Type a value in chat"));assertTrue(g.contains("intentionalEditorClose.add"));assertTrue(g.contains("p.closeInventory();Bukkit.getScheduler().runTask"));assertTrue(g.contains("inputReturns.put"));assertTrue(g.contains("void cancelInput"));}
 @Test public void playerCommandValueIsNormalizedAndNotExecutedDuringEditing()throws Exception{String g=source("GuiService.java");assertTrue(g.contains("PlayerCommand.normalize(value)"));assertTrue(g.contains("Action value cannot be empty."));String edit=g.substring(g.indexOf("void editValue"),g.indexOf("void number"));assertFalse(edit.contains("actions().run"));}
 @Test public void menuIdCompletionIsLimitedToMenuSubcommands()throws Exception{String s=source("ZGuiCommand.java");assertTrue(s.contains("Arrays.asList(\"edit\",\"open\",\"preview\",\"duplicate\",\"delete\",\"export\")"));}
}