package net.zartra.gui;
import java.nio.charset.Charset;import java.nio.file.Files;import java.nio.file.Paths;import org.junit.Test;import static org.junit.Assert.*;
public class EditorNavigationCoverageTest {
 private String source(String name)throws Exception{return new String(Files.readAllBytes(Paths.get("src/main/java/net/zartra/gui/"+name)),Charset.forName("UTF-8"));}
 @Test public void visibleActionAndItemControlsHaveRoutes()throws Exception{String gui=source("GuiService.java"),listener=source("GuiListener.java");assertTrue(gui.contains("Screen.ACTION_TYPES"));assertTrue(listener.contains("Screen.ACTION_TYPES"));assertTrue(gui.contains("Screen.ITEM_FLAGS"));assertTrue(listener.contains("Screen.ITEM_FLAGS"));assertTrue(listener.contains("raw==25)gui.itemSettings"));assertTrue(listener.contains("if(!d.items.containsKey(raw))"));}
 @Test public void everyDeclaredScreenIsRoutedOrRuntimeOnly()throws Exception{String manager=source("MenuManager.java"),listener=source("GuiListener.java");String body=manager.substring(manager.indexOf("enum Screen{"),manager.indexOf("}static final class Holder"));for(String name:body.substring("enum Screen{".length()).split(",")){String screen=name.trim();if(screen.length()==0||"NONE".equals(screen))continue;assertTrue("missing route for "+screen,listener.contains("Screen."+screen));}}
 @Test public void menuListPaginationHasProtectedForwardAndBackRoutes()throws Exception{String gui=source("GuiService.java"),listener=source("GuiListener.java");assertTrue(gui.contains("void list(Player p,int requested)"));assertTrue(gui.contains("Previous page"));assertTrue(gui.contains("Next page"));assertTrue(listener.contains("raw==45&&page>1"));assertTrue(listener.contains("raw==53"));}
 @Test public void chatCancellationRestoresTheOriginatingEditor()throws Exception{String gui=source("GuiService.java"),listener=source("GuiListener.java");assertTrue(gui.contains("inputReturns.put"));assertTrue(gui.contains("void cancelInput"));assertTrue(listener.contains("gui.cancelInput"));assertTrue(listener.contains("gui.inputFinished"));}
 @Test public void expiredChatInputIsCleanedAndReturned()throws Exception{String input=source("ChatInputManager.java"),listener=source("GuiListener.java");assertTrue(input.contains("boolean expired"));assertTrue(listener.contains("plugin.inputs().expired(x)"));assertTrue(listener.contains("Input timed out."));}
 @Test public void clipboardAndClearControlsHaveProtectedRoutes()throws Exception{String gui=source("GuiService.java"),listener=source("GuiListener.java");assertTrue(gui.contains("void copyItem"));assertTrue(gui.contains("void pasteItem"));assertTrue(gui.contains("Screen.CLEAR_MENU"));assertTrue(listener.contains("gui.copyItem"));assertTrue(listener.contains("gui.pasteItem"));assertTrue(listener.contains("gui.clearMenuConfirm"));}
 @Test public void historyHasConnectedUndoAndRedoRoutes()throws Exception{String gui=source("GuiService.java"),listener=source("GuiListener.java");assertTrue(gui.contains("void checkpoint("));assertTrue(gui.contains("void undo("));assertTrue(gui.contains("void redo("));assertTrue(listener.contains("ClickType.CONTROL_DROP"));assertTrue(listener.contains("gui.undo"));assertTrue(listener.contains("gui.redo"));}
 @Test public void nestedConditionActionListsAreConnected()throws Exception{String gui=source("GuiService.java"),listener=source("GuiListener.java");assertTrue(gui.contains("void nestedActionList"));assertTrue(gui.contains("void addNestedAction"));assertTrue(gui.contains("On success"));assertTrue(gui.contains("On failure"));assertTrue(listener.contains("Screen.NESTED_ACTION_LIST"));assertTrue(listener.contains("gui.nestedActionList"));}
 @Test public void lifecycleOpeningConditionAndPaginationEditorsAreConnected()throws Exception{String gui=source("GuiService.java"),listener=source("GuiListener.java");assertTrue(gui.contains("void paginationSettings"));assertTrue(gui.contains("void navigationMaterial"));assertTrue(gui.contains("void menuOpenConditionEdit"));assertTrue(gui.contains("void menuActionEdit"));assertTrue(listener.contains("Screen.PAGINATION_SETTINGS"));assertTrue(listener.contains("Screen.NAVIGATION_MATERIAL"));assertTrue(listener.contains("Screen.MENU_OPEN_CONDITION_EDIT"));assertTrue(listener.contains("Screen.MENU_ACTION_EDIT"));}@Test public void visualEditorNavigationPersistsBeforeOpeningSubEditors()throws Exception{String gui=source("GuiService.java"),listener=source("GuiListener.java");assertTrue(gui.contains("void leaveVisual"));assertTrue(gui.contains("saveEditor(i)"));assertTrue(listener.contains("gui.leaveVisual(p,d);"));assertTrue(listener.contains("top.setItem(raw,new ItemStack(Material.STONE))"));} @Test public void chatInputDoesNotReplaceAnExistingSession()throws Exception{String input=source("ChatInputManager.java"),gui=source("GuiService.java");assertTrue(input.contains("if(map.containsKey(p.getUniqueId()))return false"));assertTrue(gui.contains("intentionalEditorClose.add"));}
}