package net.zartra.gui;
import static org.junit.Assert.*;import org.bukkit.Material;import org.bukkit.inventory.ItemStack;import org.junit.Test;
public class LeatherColorPickerTest {
 @Test public void rgbParserSupportsCompleteRangeAndRejectsInvalid(){assertArrayEquals(new int[]{255,0,0},LeatherColorCompat.rgb("255,0,0"));assertArrayEquals(new int[]{0,255,255},LeatherColorCompat.rgb("0,255,255"));assertNull(LeatherColorCompat.rgb("-1,0,0"));assertNull(LeatherColorCompat.rgb("256,0,0"));assertNull(LeatherColorCompat.rgb("blue"));}
 @Test public void hexFormattingIsExact(){assertEquals("#FF0000",LeatherColorCompat.hex("255,0,0"));assertEquals("#00FF00",LeatherColorCompat.hex("0,255,0"));assertEquals("#0000FF",LeatherColorCompat.hex("0,0,255"));}
 @Test public void leatherCapabilityIsMetaBasedAndNonLeatherIsExcluded()throws Exception{String source=new String(java.nio.file.Files.readAllBytes(java.nio.file.Paths.get("src/main/java/net/zartra/gui/LeatherColorCompat.java")),"UTF-8");assertTrue(source.contains("getMethod(\"setColor\",Color.class)"));assertFalse(source.contains("contains(\"LEATHER\")"));assertFalse(LeatherColorCompat.capable(new MenuItem(new ItemStack(Material.STONE),null)));}
 @Test public void pickerContainsFamiliesVariantsAndControls()throws Exception{String source=new String(java.nio.file.Files.readAllBytes(java.nio.file.Paths.get("src/main/java/net/zartra/gui/GuiService.java")),"UTF-8");assertTrue(GuiService.LEATHER_PRESETS.length>=20);assertTrue(source.contains("Leather Color Picker"));assertTrue(source.contains("Custom RGB"));assertTrue(source.contains("Custom HEX"));assertTrue(source.contains("Reset to Default Leather Color"));assertTrue(source.contains("&aApply"));assertTrue(source.contains("Cancel / Back"));}
 @Test public void colorStateAndSnapshotRoundTripArePersisted()throws Exception{String item=new String(java.nio.file.Files.readAllBytes(java.nio.file.Paths.get("src/main/java/net/zartra/gui/MenuItem.java")),"UTF-8");String storage=new String(java.nio.file.Files.readAllBytes(java.nio.file.Paths.get("src/main/java/net/zartra/gui/MenuStorage.java")),"UTF-8");assertTrue(item.contains("boolean leatherDefault"));assertTrue(storage.contains("leather-default"));assertTrue(storage.contains("leather-color"));}
 @Test public void previewOnlyAppliesOnExplicitApply()throws Exception{String source=new String(java.nio.file.Files.readAllBytes(java.nio.file.Paths.get("src/main/java/net/zartra/gui/GuiService.java")),"UTF-8");assertTrue(source.contains("void selectLeatherPreview"));assertTrue(source.contains("void applyLeatherColor"));assertTrue(source.substring(source.indexOf("void applyLeatherColor"),source.indexOf("void cancelLeatherPreview")).contains("checkpoint(p,d)"));assertTrue(source.contains("void cancelLeatherPreview"));}
}