package net.zartra.gui;
import java.lang.reflect.*;import java.nio.charset.Charset;import java.nio.file.*;import java.util.*;import org.bukkit.*;import org.bukkit.entity.Player;import org.bukkit.plugin.PluginManager;import org.bukkit.scheduler.BukkitScheduler;import org.junit.*;import static org.junit.Assert.*;
public class ModernCompatibilityPlayerCommandTest {
 private static List<String> commands;private static boolean handled;
 @Before public void reset(){commands=new ArrayList<String>();handled=true;System.setProperty("zartragui.server-name","fallback-server");ServerNameResolver.clearForTests();}
 @Test public void noProductionSourceDirectlyLinksGetServerName()throws Exception{for(Path p:(Iterable<Path>)Files.walk(Paths.get("src/main/java")).filter(x->x.toString().endsWith(".java"))::iterator)assertFalse(p.toString(),new String(Files.readAllBytes(p),Charset.forName("UTF-8")).contains("Bukkit.getServerName("));}
 @Test public void serverPlaceholderUsesReflectionFallbackWithoutMethod(){assertEquals("fallback-server",new PlaceholderService().replace(null,new MenuDefinition("id","T",3),"%server%"));}
 @Test public void commandNormalizationCoversLegacyAndMultipleSlashes(){assertEquals("spawn",PlayerCommand.normalize(" spawn "));assertEquals("spawn",PlayerCommand.normalize("/spawn"));assertEquals("warp lobby",PlayerCommand.normalize("//warp lobby"));assertNull(PlayerCommand.normalize(" /// "));}
 @Test public void codecNormalizesLegacySlashValue(){Map<String,Object> raw=new HashMap<String,Object>();raw.put("type","PLAYER_COMMAND");raw.put("value","/spawn");ActionEntry a=ActionCodec.read(raw);assertEquals("spawn",a.value);assertEquals("spawn",ActionCodec.write(a).get("value"));}
 @Test public void runtimeDispatchesCanonicalAndLegacyCommandExactlyOnce(){ActionEntry a=new ActionEntry();a.type="PLAYER_COMMAND";a.value="/warp lobby";new ActionExecutor(null,null).run(player(),new MenuDefinition("id","T",3),Collections.singletonList(a));assertEquals(Collections.singletonList("warp lobby"),commands);}
 @Test public void falsePlayerDispatchIsNotReportedAsSuccess(){handled=false;ActionEntry a=new ActionEntry();a.type="PLAYER_COMMAND";a.value="spawn";a.stopOnFailure=true;ActionEntry after=new ActionEntry();after.type="MESSAGE";after.value="after";new ActionExecutor(null,null).run(player(),new MenuDefinition("id","T",3),Arrays.asList(a,after));assertEquals(Collections.singletonList("spawn"),commands);}
 private Player player(){return (Player)Proxy.newProxyInstance(getClass().getClassLoader(),new Class[]{Player.class},new InvocationHandler(){public Object invoke(Object p,Method m,Object[] a){if("isOnline".equals(m.getName()))return true;if("performCommand".equals(m.getName())){commands.add((String)a[0]);return handled;}if("getName".equals(m.getName())||"getDisplayName".equals(m.getName()))return "Alex";if("getUniqueId".equals(m.getName()))return new UUID(0,2);if("getWorld".equals(m.getName()))return null;return fallback(m.getReturnType());}});}
 private static Object fallback(Class<?> c){if(c==Boolean.TYPE)return false;if(c==Integer.TYPE)return 0;if(c==Long.TYPE)return 0L;if(c==Double.TYPE)return 0D;if(c==Float.TYPE)return 0F;return null;}
}