package net.zartra.gui;
import static org.junit.Assert.*;import java.nio.charset.Charset;import java.nio.file.*;import org.junit.Test;
public class RgbPickerRegressionTest {
 private String source(String n)throws Exception{return new String(Files.readAllBytes(Paths.get("src/main/java/net/zartra/gui/"+n)),Charset.forName("UTF-8"));}
 @Test public void componentSenderNeverStringifiesComponents()throws Exception{String s=source("ChatComponentCompat.java");assertTrue(s.contains("boolean send"));assertTrue(s.contains("Player.class.getMethod(\"spigot\")"));assertTrue(s.contains("target.invoke(bridge,array)"));assertFalse(s.contains("fallback.append"));assertFalse(s.contains("p.sendMessage(fallback"));assertFalse(s.contains("toString()"));}
 @Test public void unavailableComponentsReturnToInventorySafely()throws Exception{String s=source("ChatColorPicker.java");assertTrue(s.contains("Interactive chat components are unavailable"));assertTrue(s.contains("gui.leatherPicker"));assertTrue(s.contains("throw new IllegalStateException"));}
 @Test public void hueCellsKeepClickAndHoverMetadata()throws Exception{String s=source("ChatComponentCompat.java");assertTrue(s.contains("setClickEvent"));assertTrue(s.contains("setHoverEvent"));assertTrue(s.contains("RUN_COMMAND"));assertTrue(s.contains("Approximate legacy preview"));}
 @Test public void confirmationsUseUnambiguousMaterials()throws Exception{String s=source("GuiService.java");assertTrue(s.contains("Material.EMERALD"));assertTrue(s.contains("Material.REDSTONE"));assertFalse(s.contains("LIME_TERRACOTTA"));assertFalse(s.contains("STAINED_CLAY"));assertTrue(s.contains("confirmation(true,\"&aConfirm delete\")"));assertTrue(s.contains("confirmation(false,\"&cCancel\")"));}
 @Test public void allDestructiveConfirmationsUseFactory()throws Exception{String s=source("GuiService.java");assertTrue(s.contains("void deleteItemConfirm"));assertTrue(s.contains("void clearMenuConfirm"));assertTrue(s.contains("void moveConfirm"));assertTrue(s.contains("confirmation(true,\"&aSave Changes\")"));}
 @Test public void provisionalColorSurvivesModalAndChatTransitions()throws Exception{String gui=source("GuiService.java"),picker=source("ChatColorPicker.java");assertTrue(gui.contains("suspendLeatherPicker(p);ask"));assertTrue(gui.contains("pendingLeatherColors"));assertTrue(gui.contains("pendingLeatherDefaults"));assertTrue(gui.contains("consumeLeatherPickerTransition"));assertTrue(picker.contains("enteredDefault"));assertTrue(picker.contains("gui.setLeatherPreview(p,s.entered,s.enteredDefault)"));assertTrue(picker.contains("gui.setLeatherPreview(p,s.selected,s.defaultSelected)"));}
 @Test public void paletteStateDoesNotCreateUndoBeforeApply()throws Exception{String s=source("GuiService.java");int begin=s.indexOf("void selectLeatherPreview"),apply=s.indexOf("void applyLeatherColor");assertFalse(s.substring(begin,apply).contains("checkpoint(p,d)"));assertTrue(s.substring(apply,s.indexOf("void cancelLeatherPreview")).contains("checkpoint(p,d)"));}
}