package net.zartra.gui;
import java.util.*;
import org.bukkit.command.*;
import org.bukkit.entity.Player;
/** Dynamic menu aliases isolated behind the stable Bukkit CommandMap API. */
final class AliasRegistry {
 private final ZartraGUIPlugin plugin; private final MenuManager menus; private final Map<String,Command> registered=new LinkedHashMap<String,Command>();
 AliasRegistry(ZartraGUIPlugin plugin,MenuManager menus){this.plugin=plugin;this.menus=menus;}
 synchronized void refresh(){clear(); for(MenuDefinition menu:menus.all())if(menu.commandTarget==MenuDefinition.CommandTarget.REQUIRED&&menu.commandAliases.isEmpty())plugin.getLogger().warning("Menu "+menu.id+" requires a command target but has no aliases."); CommandMap map=map(); if(map==null){plugin.getLogger().warning("Dynamic menu aliases are unavailable: server command map could not be resolved.");return;} Set<String> wanted=new LinkedHashSet<String>(); for(MenuDefinition menu:menus.all()){for(String raw:menu.commandAliases){String alias=PlayerCommand.normalize(raw);if(alias==null||!alias.matches("[A-Za-z0-9_.-]{1,64}")){plugin.getLogger().warning("Ignoring invalid alias in "+menu.id+": "+raw);continue;}alias=alias.toLowerCase(Locale.ENGLISH);if(!wanted.add(alias)){plugin.getLogger().warning("Ignoring duplicate menu alias: /"+alias);continue;}Command prior=map.getCommand(alias);if(prior!=null){plugin.getLogger().warning("Alias /"+alias+" for "+menu.id+" conflicts with an existing command and was not registered.");continue;}Command command=new MenuAliasCommand(alias,menu.id);if(map.register(plugin.getDescription().getName().toLowerCase(Locale.ENGLISH),command))registered.put(alias,command);else plugin.getLogger().warning("Server rejected alias /"+alias+" for "+menu.id);}}}
 synchronized void clear(){CommandMap map=map();if(map!=null)for(Command command:registered.values())try{command.unregister(map);}catch(LinkageError e){plugin.getLogger().warning("Unable to unregister menu alias: "+e.getMessage());}registered.clear();}
 private CommandMap map(){try{java.lang.reflect.Method m=plugin.getServer().getClass().getMethod("getCommandMap");Object result=m.invoke(plugin.getServer());return result instanceof CommandMap?(CommandMap)result:null;}catch(Throwable ignored){}try{java.lang.reflect.Field f=plugin.getServer().getClass().getDeclaredField("commandMap");f.setAccessible(true);Object result=f.get(plugin.getServer());return result instanceof CommandMap?(CommandMap)result:null;}catch(Throwable ignored){return null;}}
 private final class MenuAliasCommand extends Command {
  private final String menuId; MenuAliasCommand(String alias,String menuId){super(alias);this.menuId=menuId;setDescription("Open ZartraGUI menu "+menuId);}
  public boolean execute(CommandSender sender,String label,String[] args){MenuDefinition menu=menus.get(menuId);if(menu==null){sender.sendMessage(Chat.c("&cThis menu no longer exists."));return true;}if(!(sender instanceof Player)){sender.sendMessage(Chat.c("&cThis menu command must be used by a player."));return true;}Player actor=(Player)sender;if(menu.commandTarget==MenuDefinition.CommandTarget.REQUIRED&&args.length!=1){actor.sendMessage(Chat.c("&eUsage: /"+label+" <player>"));return true;}if(menu.commandTarget==MenuDefinition.CommandTarget.DISABLED&&args.length>0){actor.sendMessage(Chat.c("&cThis menu does not accept a target."));return true;}Player target=actor;if(args.length==1){if(menu.commandTarget==MenuDefinition.CommandTarget.DISABLED){actor.sendMessage(Chat.c("&cThis menu does not accept a target."));return true;}if(!actor.hasPermission("zartragui.open.others")){actor.sendMessage(Chat.c("&cYou do not have permission to open menus for others."));return true;}target=org.bukkit.Bukkit.getPlayerExact(args[0]);if(target==null){actor.sendMessage(Chat.c("&cPlayer not found."));return true;}}else if(args.length>1){actor.sendMessage(Chat.c("&eUsage: /"+label+(menu.commandTarget==MenuDefinition.CommandTarget.REQUIRED?" <player>":" [player]")));return true;}menus.open(target,menu);return true;}
  public List<String> tabComplete(CommandSender sender,String alias,String[] args){MenuDefinition menu=menus.get(menuId);if(menu==null||menu.commandTarget==MenuDefinition.CommandTarget.DISABLED||args.length!=1)return Collections.emptyList();List<String> out=new ArrayList<String>();for(Player player:org.bukkit.Bukkit.getOnlinePlayers())if(player.getName().toLowerCase(Locale.ENGLISH).startsWith(args[0].toLowerCase(Locale.ENGLISH)))out.add(player.getName());return out;}
 }
}