package net.zartra.gui;
import java.lang.reflect.*;import java.util.*;import org.bukkit.entity.Player;
/** Reflection-only bridge: production bytecode has no Bungee or Adventure linkage. */
final class ChatComponentCompat {
 private ChatComponentCompat(){}
 static Object cell(String text,int[] rgb,String command,String hover){try{Class<?> base=Class.forName("net.md_5.bungee.api.chat.BaseComponent"),tc=Class.forName("net.md_5.bungee.api.chat.TextComponent"),color=Class.forName("net.md_5.bungee.api.ChatColor"),click=Class.forName("net.md_5.bungee.api.chat.ClickEvent"),clickAction=Class.forName("net.md_5.bungee.api.chat.ClickEvent$Action"),hoverClass=Class.forName("net.md_5.bungee.api.chat.HoverEvent"),hoverAction=Class.forName("net.md_5.bungee.api.chat.HoverEvent$Action");Object c=tc.getConstructor(String.class).newInstance(text);Object chosen;try{chosen=color.getMethod("of",String.class).invoke(null,ChatColorPalette.hex(rgb));}catch(Throwable modernMissing){chosen=color.getMethod("getByChar",char.class).invoke(null,Character.valueOf(ChatColorPalette.legacy(rgb).charAt(0)));hover+="\nApproximate legacy preview.";}base.getMethod("setColor",color).invoke(c,chosen);Object run=Enum.valueOf((Class)clickAction,"RUN_COMMAND");Object ce=click.getConstructor(clickAction,String.class).newInstance(run,command);base.getMethod("setClickEvent",click).invoke(c,ce);Object show=Enum.valueOf((Class)hoverAction,"SHOW_TEXT");Object harray=Array.newInstance(base,1);Array.set(harray,0,tc.getConstructor(String.class).newInstance(hover));Object he=hoverClass.getConstructor(hoverAction,harray.getClass()).newInstance(show,harray);base.getMethod("setHoverEvent",hoverClass).invoke(c,he);return c;}catch(Throwable unavailable){return text;}}
 static Object control(String label,String command){return cell(label,new int[]{85,255,255},command,label);}
 static Object plain(String text){try{return Class.forName("net.md_5.bungee.api.chat.TextComponent").getConstructor(String.class).newInstance(text);}catch(Throwable ignored){return text;}}
 static void send(Player p,Object... components){try{Class<?> base=Class.forName("net.md_5.bungee.api.chat.BaseComponent");Object array=Array.newInstance(base,components.length);for(int i=0;i<components.length;i++)Array.set(array,i,components[i]);Object spigot=p.getClass().getMethod("spigot").invoke(p);Method send=spigot.getClass().getMethod("sendMessage",array.getClass());send.invoke(spigot,array);}catch(Throwable legacy){StringBuilder fallback=new StringBuilder();for(Object c:components)fallback.append(c==null?"":c.toString());p.sendMessage(fallback.toString());}}
}