package net.zartra.gui;
import java.security.SecureRandom;import java.util.*;import org.bukkit.entity.Player;
/** Opaque, one-player chat picker sessions. Commands never carry menu or colour data. */
final class ChatColorPicker {
 private static final long TTL=5L*60L*1000L;private final ZartraGUIPlugin plugin;private final GuiService gui;private final Map<String,Session> sessions=new HashMap<String,Session>();private final SecureRandom random=new SecureRandom();
 static final class Session{final String token;final UUID player;final String menu;final int slot,page;final long created,expires;final String entered;final boolean enteredDefault;int hue;String selected;boolean defaultSelected;Session(String t,Player p,MenuDefinition d,int slot,int page,String selected,boolean reset){token=t;player=p.getUniqueId();menu=d.id;this.slot=slot;this.page=page;if(!reset&&LeatherColorCompat.rgb(selected)==null)reset=true;this.selected=selected;defaultSelected=reset;entered=this.selected;enteredDefault=reset;created=System.currentTimeMillis();expires=created+TTL;}}
 ChatColorPicker(ZartraGUIPlugin p,GuiService g){plugin=p;gui=g;}private String token(){byte[] b=new byte[18];random.nextBytes(b);StringBuilder out=new StringBuilder();for(byte x:b)out.append(String.format("%02x",x&255));return out.toString();}private void purge(){long now=System.currentTimeMillis();Iterator<Session> it=sessions.values().iterator();while(it.hasNext())if(it.next().expires<now)it.remove();}
 void open(final Player p,MenuDefinition d,int slot,int page,String selected,boolean reset){purge();final String t=token();final Session s=new Session(t,p,d,slot,page,selected,reset);sessions.put(t,s);gui.suspendLeatherPicker(p);p.closeInventory();plugin.getServer().getScheduler().runTask(plugin,new Runnable(){public void run(){if(p.isOnline()&&sessions.get(t)==s)display(p,s,0);}});}void clear(Player p){Iterator<Session> it=sessions.values().iterator();while(it.hasNext())if(it.next().player.equals(p.getUniqueId()))it.remove();}void clearAll(){sessions.clear();}
 boolean handle(Player p,String token,String action){purge();Session s=sessions.get(token);if(s==null||!s.player.equals(p.getUniqueId())){p.sendMessage(Chat.c("&cPicker Expired."));return true;}if(!action.matches("(?:h[0-9]{1,2}|shade[0-9]{1,2}|prev|next|spectrum|default|apply|choose|back|cancel)")){p.sendMessage(Chat.c("&cPicker Expired."));return true;}MenuDefinition d=plugin.menus().get(s.menu);if(d==null||s.slot<0||d.items.get(s.slot)==null){sessions.remove(token);p.sendMessage(Chat.c("&cPicker Expired."));return true;}if("cancel".equals(action)){sessions.remove(token);gui.setLeatherPreview(p,s.entered,s.enteredDefault);gui.leatherPicker(p,d,s.slot,s.page);return true;}if("back".equals(action)){sessions.remove(token);gui.setLeatherPreview(p,s.selected,s.defaultSelected);gui.leatherPicker(p,d,s.slot,s.page);return true;}if("apply".equals(action)){if(!p.hasPermission("zartragui.edit")&&!p.hasPermission("zartragui.admin")){p.sendMessage(Chat.c("&cYou do not have permission."));return true;}sessions.remove(token);gui.setLeatherPreview(p,s.selected,s.defaultSelected);gui.applyLeatherColor(p,d,s.slot);return true;}if("default".equals(action)){s.defaultSelected=true;s.selected="";display(p,s,2);return true;}if("choose".equals(action)){display(p,s,1);return true;}if("spectrum".equals(action)){display(p,s,0);return true;}if("prev".equals(action)){s.hue=(s.hue+29)%30;display(p,s,1);return true;}if("next".equals(action)){s.hue=(s.hue+1)%30;display(p,s,1);return true;}if(action.startsWith("h")){s.hue=Integer.parseInt(action.substring(1));if(s.hue<0||s.hue>=30){p.sendMessage(Chat.c("&cPicker Expired."));return true;}display(p,s,1);return true;}if(action.startsWith("shade")){int n=Integer.parseInt(action.substring(5));if(n<0||n>=64){p.sendMessage(Chat.c("&cPicker Expired."));return true;}s.selected=ChatColorPalette.rgb(ChatColorPalette.shades(s.hue)[n]);s.defaultSelected=false;display(p,s,2);return true;}p.sendMessage(Chat.c("&cPicker Expired."));return true;}
 private String cmd(Session s,String a){return "/_zgui_picker "+s.token+" "+a;}private void display(Player p,Session s,int view){try{if(view==0)spectrum(p,s);else if(view==1)shade(p,s);else preview(p,s);}catch(IllegalStateException unavailable){sessions.remove(s.token);p.sendMessage(Chat.c("&cInteractive chat components are unavailable; returning to the inventory picker."));gui.setLeatherPreview(p,s.selected,s.defaultSelected);MenuDefinition d=plugin.menus().get(s.menu);if(d!=null)gui.leatherPicker(p,d,s.slot,s.page);}}private void line(Player p,Object... c){if(!ChatComponentCompat.send(p,c))throw new IllegalStateException("component sender unavailable");}private String glyph(){return "\u25A0";}
 private void spectrum(Player p,Session s){p.sendMessage(" ");p.sendMessage(" ");p.sendMessage(Chat.c("&b&lFull Spectrum &7- Select a Hue"));int[][] hues=ChatColorPalette.hues();for(int row=0;row<3;row++){List<Object> parts=new ArrayList<Object>();for(int col=0;col<10;col++){int n=row*10+col;int[] c=hues[n];parts.add(ChatComponentCompat.cell(glyph(),c,cmd(s,"h"+n),ChatColorPalette.hover(c,"Hue: "+(n*12)+"\nClick to view shades")));}line(p,parts.toArray());}int[] gray={160,160,160};line(p,ChatComponentCompat.cell(glyph()+glyph()+glyph()+glyph()+glyph()+glyph()+glyph()+glyph(),gray,cmd(s,"h0"),ChatColorPalette.hover(gray,"Grayscale is available in every shade grid.")));controls(p,s,"[BACK TO LEATHER COLOR PICKER]","back","[DEFAULT LEATHER COLOR]","default","[CANCEL]","cancel");}
 private void shade(Player p,Session s){p.sendMessage(Chat.c("&b&lSelect a Shade &7- Hue "+(s.hue*12)));int[][] cells=ChatColorPalette.shades(s.hue);for(int row=0;row<8;row++){List<Object> parts=new ArrayList<Object>();for(int col=0;col<8;col++){int n=row*8+col;int[] c=cells[n];float sat=col/7f,val=.18f+(.82f*(7-row)/7f);parts.add(ChatComponentCompat.cell(glyph(),c,cmd(s,"shade"+n),ChatColorPalette.hover(c,"Hue: "+(s.hue*12)+"\nSaturation: "+Math.round(sat*100)+"%\nBrightness: "+Math.round(val*100)+"%\nClick to select")));}line(p,parts.toArray());}controls(p,s,"[PREVIOUS HUE]","prev","[NEXT HUE]","next","[FULL SPECTRUM]","spectrum","[BACK TO INVENTORY PICKER]","back","[CANCEL]","cancel");}
 private void preview(Player p,Session s){int[] c=s.defaultSelected?new int[]{160,101,64}:LeatherColorCompat.rgb(s.selected);p.sendMessage(Chat.c("&a&lSelected Color: "));line(p,ChatComponentCompat.cell(glyph()+glyph()+glyph()+glyph()+glyph(),c,cmd(s,"choose"),ChatColorPalette.hover(c,"Click to choose another color")));p.sendMessage(Chat.c("&7HEX: &f"+(s.defaultSelected?"Default":ChatColorPalette.hex(c))+" &7RGB: &f"+(s.defaultSelected?"Default":ChatColorPalette.rgb(c))));controls(p,s,"[APPLY]","apply","[CHOOSE ANOTHER COLOR]","choose","[BACK TO INVENTORY PICKER]","back","[CANCEL]","cancel");}
 private void controls(Player p,Session s,String... values){List<Object> out=new ArrayList<Object>();for(int i=0;i<values.length;i+=2){if(!out.isEmpty())out.add(ChatComponentCompat.plain(" "));out.add(ChatComponentCompat.control(values[i],cmd(s,values[i+1])));}line(p,out.toArray());}
}