package net.zartra.gui;
import java.util.*;import org.bukkit.*;import org.bukkit.entity.Player;import org.bukkit.inventory.ItemStack;
final class ConditionEvaluator {private final PlaceholderService placeholders;private final VariableStore variables;private final ConditionRegistry registry=new ConditionRegistry();private final VaultAdapter vault=new VaultAdapter();ConditionEvaluator(){this(new VariableStore(),new PlaceholderService());}ConditionEvaluator(VariableStore v,PlaceholderService p){variables=v;placeholders=p;}
 boolean test(Player p,MenuDefinition menu,ConditionEntry c){if(c==null||!c.enabled)return true;if(!registry.valid(c))return false;boolean result=false;String v=placeholders.replace(p,menu,c.value);try{switch(c.type){case HAS_PERMISSION:result=p.hasPermission(v);break;case NOT_HAS_PERMISSION:result=!p.hasPermission(v);break;case HAS_LEVEL:case MIN_LEVEL:result=p.getLevel()>=Integer.parseInt(v);break;case MAX_LEVEL:result=p.getLevel()<=Integer.parseInt(v);break;case IS_OP:result=p.isOp();break;case IS_NOT_OP:result=!p.isOp();break;case GAMEMODE:result=p.getGameMode().name().equalsIgnoreCase(v);break;case WORLD:result=p.getWorld().getName().equalsIgnoreCase(v);break;case SERVER:result=ServerNameResolver.resolve().equalsIgnoreCase(v);break;case PLAYER_NAME:result=p.getName().equalsIgnoreCase(v);break;case IS_SNEAKING:result=p.isSneaking();break;case IS_FLYING:result=p.isFlying();break;case CHANCE:result=Math.random()*100D<=Double.parseDouble(v);break;case HAS_ITEM:result=hasItem(p,v,false);break;case HAS_EXACT_ITEM:result=hasItem(p,v,true);break;case VARIABLE_EQUALS:result=variable(p,v);break;case PLACEHOLDER_EQUALS:result=pair(v,false);break;case PLACEHOLDER_CONTAINS:result=pair(v,true);break;case PLACEHOLDER_NUMBER:result=number(v);break;case TIME_RANGE:result=time(p,v);break;case COOLDOWN_READY:result=true;break;case HAS_MONEY:result=VaultAdapter.validAmount(v)&&vault.hasMoney(p,Double.parseDouble(v));break;default:result=false;}}catch(Exception ignored){result=false;}return c.inverted?!result:result;}
 boolean testEntries(Player p,MenuDefinition m,List<ConditionEntry> entries,ConditionSet.Mode mode){if(entries==null||entries.isEmpty())return true;boolean any=false;for(ConditionEntry c:entries){boolean ok=test(p,m,c);if(mode==ConditionSet.Mode.AND&&!ok)return false;if(mode==ConditionSet.Mode.OR&&ok)return true;any=true;}return mode==ConditionSet.Mode.AND||!any;}
 boolean testSet(Player p,MenuDefinition m,ConditionSet set){return set==null||testEntries(p,m,set.ordered(),set.mode);}
 private boolean hasItem(Player p,String raw,boolean exact){String[] a=raw.split(":",2);Material mat=CompatMaterial.find(a[0]);int need=a.length>1?Integer.parseInt(a[1]):1,count=0;for(ItemStack i:p.getInventory().getContents())if(i!=null&&i.getType()==mat&&(!exact||i.getDurability()==0))count+=i.getAmount();return count>=need;}
 private boolean variable(Player p,String v){String[] a=v.split("=",2);if(a.length!=2)return false;String actual=variables.resolve(p.getUniqueId(),null,a[0]);return a[1].equals(actual);}
 private boolean pair(String v,boolean contains){String[] a=v.split("\\|",2);if(a.length!=2)return false;return contains?a[0].contains(a[1]):a[0].equals(a[1]);}
 private boolean number(String v){String[] a=v.split("\\|",3);if(a.length!=3)return false;double x=Double.parseDouble(a[0]),n=Double.parseDouble(a[2]);return ">".equals(a[1])?x>n:">=".equals(a[1])?x>=n:"<".equals(a[1])?x<n:"<=".equals(a[1])?x<=n:"=".equals(a[1])?x==n:false;}
 private boolean time(Player p,String v){String[] a=v.split("-",2);long from=Long.parseLong(a[0]),to=Long.parseLong(a[1]),now=p.getWorld().getTime();return from<=to?now>=from&&now<=to:now>=from||now<=to;}
}