package net.zartra.gui;

import java.io.*;
import java.util.*;
import java.util.logging.Logger;
import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.configuration.file.YamlConfiguration;
import org.bukkit.inventory.ItemStack;

final class MenuStorage {
 private final File dir; private final Logger log;
 MenuStorage(File dir, Logger log){this.dir=dir;this.log=log;}
 Map<String,MenuDefinition> load(){
  Map<String,MenuDefinition> result=new TreeMap<String,MenuDefinition>(); if(!dir.exists())dir.mkdirs(); File[] files=dir.listFiles(); if(files==null)return result;
  for(File file:files)if(file.isFile()&&file.getName().endsWith(".yml"))try{YamlConfiguration yaml=YamlConfiguration.loadConfiguration(file); boolean legacy=hasLegacyActions(yaml); MenuDefinition menu=read(yaml); if(menu!=null){result.put(menu.id,menu);if(legacy){File backup=new File(file.getParentFile(),file.getName()+".pre-action-migration.bak");if(!backup.exists())copy(file,backup);save(menu);}}}catch(Exception ex){log.warning("Could not load "+file.getName()+": "+ex.getMessage());}
  return result;
 }
 private static boolean hasLegacyActions(YamlConfiguration yaml){ConfigurationSection items=yaml.getConfigurationSection("items");if(items==null)return false;for(String key:items.getKeys(false)){ConfigurationSection item=items.getConfigurationSection(key);if(item!=null&&item.contains("action")&&!item.contains("actions"))return true;}return false;} private static void copy(File from,File to)throws IOException{InputStream input=new FileInputStream(from);OutputStream output=new FileOutputStream(to);byte[] buffer=new byte[8192];int count;while((count=input.read(buffer))>0)output.write(buffer,0,count);input.close();output.close();}
 private MenuDefinition read(YamlConfiguration yaml)throws IOException{
  String id=yaml.getString("id"); if(!MenuManager.validId(id))throw new IOException("missing or unsafe id");
  MenuDefinition menu=new MenuDefinition(id,yaml.getString("title",id),yaml.getInt("rows",3)); menu.formatVersion=Math.max(1,yaml.getInt("format-version",1));
  menu.inventoryType=InventoryCompat.safeType(yaml.getString("inventory-type","CHEST")); menu.playerInventoryInteraction=yaml.getBoolean("player-inventory-interaction",false); menu.itemsTakeable=yaml.getBoolean("items-takeable",false); menu.maximumViewers=Math.max(0,yaml.getInt("maximum-viewers",0));
  menu.defaultFillerMaterial=yaml.getString("default-filler-material",""); menu.paginationPreviousMaterial=yaml.getString("pagination.previous-material","ARROW"); menu.paginationNextMaterial=yaml.getString("pagination.next-material","ARROW"); menu.paginationContentSlots.addAll(yaml.getIntegerList("pagination.content-slots"));
  menu.openingCommand=yaml.getString("opening-command",""); menu.commandAliases.addAll(yaml.getStringList("command-aliases"));try{menu.commandTarget=MenuDefinition.CommandTarget.valueOf(yaml.getString("command-target","DISABLED").toUpperCase());}catch(Exception ignored){}try{menu.worldAccess=MenuDefinition.WorldAccess.valueOf(yaml.getString("world-access.mode","ALL").toUpperCase());}catch(Exception ignored){}menu.worlds.addAll(yaml.getStringList("world-access.worlds"));menu.worldDenied=yaml.getString("world-access.denial-message",menu.worldDenied); menu.openingPermission=yaml.getString("opening-permission",""); menu.permissionDenied=yaml.getString("permission-denied",menu.permissionDenied); menu.openingSound=yaml.getString("opening-sound",""); menu.closingSound=yaml.getString("closing-sound",""); menu.refreshInterval=Math.max(0,yaml.getLong("refresh-interval",0)); menu.closeAfterAction=yaml.getBoolean("close-after-action",false); menu.createdAt=yaml.getLong("created-at",menu.createdAt); menu.modifiedAt=yaml.getLong("modified-at",menu.modifiedAt);
  menu.openActions.addAll(ActionCodec.readAll(yaml.getMapList("open-actions"))); menu.closeActions.addAll(ActionCodec.readAll(yaml.getMapList("close-actions"))); readConditionSet(yaml.getConfigurationSection("open-conditions"),menu.openConditions);
  ConfigurationSection items=yaml.getConfigurationSection("items"); if(items!=null)for(String key:items.getKeys(false))try{int slot=Integer.parseInt(key); if(slot<0||slot>=menu.rows*9)continue; ConfigurationSection section=items.getConfigurationSection(key); if(section==null)continue; MenuItem item=readItem(section); menu.items.put(slot,item);}catch(Exception ignored){}
  return menu;
 }
 private MenuItem readItem(ConfigurationSection s){
  String material=s.getString("material","STONE"); MenuItem item=new MenuItem(new ItemStack(CompatMaterial.find(material),clamp(s.getInt("amount",1),1,64)),MenuAction.parse(s.getString("action")));
  Object snapshot=s.get("stack-snapshot");if(snapshot instanceof Map)item.stackSnapshot=MenuItem.copyMap((Map<?,?>)snapshot); item.material=material; item.data=s.getInt("data",0); item.amount=clamp(s.getInt("amount",1),1,64); item.name=s.getString("name",null); item.lore=new ArrayList<String>(s.getStringList("lore")); item.glow=s.getBoolean("glow",false); item.hideEnchantments=s.getBoolean("hide-enchantments",false); item.unbreakable=s.getBoolean("unbreakable",false); item.customModelData=s.getInt("custom-model-data",-1); item.headOwner=s.getString("head-owner",""); item.leatherColor=s.getString("leather-color",""); item.potionData=s.getString("potion-data",""); item.closeAfterAction=s.getBoolean("close-after-action",false); item.cooldown=Math.max(0,s.getLong("cooldown",0)); item.priority=s.getInt("priority",0); item.fallbackMaterial=s.getString("fallback-material","");
  for(String raw:s.getStringList("enchantments")){String[] pair=raw.split(":",2);try{item.enchantments.put(pair[0].toUpperCase(),Integer.parseInt(pair[1]));}catch(Exception ignored){}}
  readConditionSet(s.getConfigurationSection("conditions"),item.conditions); ConfigurationSection actions=s.getConfigurationSection("actions"); if(actions!=null)for(String name:actions.getKeys(false))try{MenuClickType type=MenuClickType.valueOf(name); item.actions(type).addAll(ActionCodec.readAll(actions.getMapList(name)));}catch(Exception ignored){}
  if(item.action!=null)item.migrateLegacy(); return item;
 }
 void save(MenuDefinition menu)throws IOException{
  if(!dir.exists()&&!dir.mkdirs())throw new IOException("could not create menu directory"); YamlConfiguration yaml=new YamlConfiguration(); yaml.set("format-version",Math.max(3,menu.formatVersion)); yaml.set("id",menu.id); yaml.set("title",menu.title); yaml.set("rows",menu.rows); yaml.set("inventory-type",menu.inventoryType); yaml.set("player-inventory-interaction",menu.playerInventoryInteraction); yaml.set("items-takeable",menu.itemsTakeable); yaml.set("maximum-viewers",menu.maximumViewers); yaml.set("default-filler-material",menu.defaultFillerMaterial); yaml.set("pagination.previous-material",menu.paginationPreviousMaterial); yaml.set("pagination.next-material",menu.paginationNextMaterial); yaml.set("pagination.content-slots",new ArrayList<Integer>(menu.paginationContentSlots)); yaml.set("opening-command",menu.openingCommand);yaml.set("command-aliases",new ArrayList<String>(menu.commandAliases));yaml.set("command-target",menu.commandTarget.name());yaml.set("world-access.mode",menu.worldAccess.name());yaml.set("world-access.worlds",new ArrayList<String>(menu.worlds));yaml.set("world-access.denial-message",menu.worldDenied); yaml.set("opening-permission",menu.openingPermission); yaml.set("permission-denied",menu.permissionDenied); yaml.set("opening-sound",menu.openingSound); yaml.set("closing-sound",menu.closingSound); yaml.set("refresh-interval",menu.refreshInterval); yaml.set("close-after-action",menu.closeAfterAction); yaml.set("open-actions",ActionCodec.writeAll(menu.openActions)); yaml.set("close-actions",ActionCodec.writeAll(menu.closeActions)); writeConditionSet(yaml,"open-conditions",menu.openConditions); yaml.set("created-at",menu.createdAt); menu.modifiedAt=System.currentTimeMillis(); yaml.set("modified-at",menu.modifiedAt);
  List<Integer> slots=new ArrayList<Integer>(menu.items.keySet()); Collections.sort(slots); for(Integer slot:slots)writeItem(yaml,"items."+slot,menu.items.get(slot));
  File temp=new File(dir,menu.id+".tmp"), destination=new File(dir,menu.id+".yml"); yaml.save(temp); replace(temp,destination);
 }
 private void writeItem(YamlConfiguration yaml,String path,MenuItem item){
  yaml.set(path+".material",item.material); yaml.set(path+".stack-snapshot",MenuItem.copyMap(item.stackSnapshot)); yaml.set(path+".data",item.data); yaml.set(path+".amount",item.amount); yaml.set(path+".name",item.name); yaml.set(path+".lore",new ArrayList<String>(item.lore)); yaml.set(path+".glow",item.glow); yaml.set(path+".hide-enchantments",item.hideEnchantments); yaml.set(path+".unbreakable",item.unbreakable); yaml.set(path+".custom-model-data",item.customModelData); yaml.set(path+".head-owner",item.headOwner); yaml.set(path+".leather-color",item.leatherColor); yaml.set(path+".potion-data",item.potionData); yaml.set(path+".close-after-action",item.closeAfterAction); yaml.set(path+".cooldown",item.cooldown); yaml.set(path+".priority",item.priority); yaml.set(path+".fallback-material",item.fallbackMaterial);
  List<String> enchants=new ArrayList<String>(); for(Map.Entry<String,Integer> enchant:item.enchantments.entrySet())enchants.add(enchant.getKey()+":"+enchant.getValue()); Collections.sort(enchants); yaml.set(path+".enchantments",enchants); writeConditionSet(yaml,path+".conditions",item.conditions); for(MenuClickType type:MenuClickType.values())yaml.set(path+".actions."+type.name(),ActionCodec.writeAll(item.actions(type)));
 }
 private static void writeConditionSet(YamlConfiguration yaml,String path,ConditionSet set){yaml.set(path+".mode",set.mode.name());yaml.set(path+".failure-message",set.failureMessage);yaml.set(path+".hide-when-fail",set.hideWhenFail);yaml.set(path+".disable-click",set.disableClick);yaml.set(path+".stop-chain",set.stopChain);yaml.set(path+".replacement-material",set.replacementMaterial);yaml.set(path+".success-actions",ActionCodec.writeAll(set.successActions));yaml.set(path+".failure-actions",ActionCodec.writeAll(set.failureActions));List<Map<String,Object>> entries=new ArrayList<Map<String,Object>>();for(ConditionEntry c:set.ordered()){Map<String,Object> value=new LinkedHashMap<String,Object>();value.put("id",c.id);value.put("type",c.type.name());value.put("value",c.value);value.put("order",c.order);value.put("enabled",c.enabled);value.put("inverted",c.inverted);value.put("failure-message",c.failureMessage);entries.add(value);}yaml.set(path+".entries",entries);}
 private static void readConditionSet(ConfigurationSection section,ConditionSet set){if(section==null)return;try{set.mode=ConditionSet.Mode.valueOf(section.getString("mode","AND"));}catch(Exception ignored){}set.failureMessage=section.getString("failure-message","");set.hideWhenFail=section.getBoolean("hide-when-fail",false);set.disableClick=section.getBoolean("disable-click",true);set.stopChain=section.getBoolean("stop-chain",true);set.replacementMaterial=section.getString("replacement-material","");set.successActions.addAll(ActionCodec.readAll(section.getMapList("success-actions")));set.failureActions.addAll(ActionCodec.readAll(section.getMapList("failure-actions")));for(Map<?,?> raw:section.getMapList("entries"))try{ConditionEntry c=new ConditionEntry(ConditionEntry.Type.valueOf(String.valueOf(raw.get("type"))),String.valueOf(raw.get("value")));c.id=raw.get("id")==null?c.id:String.valueOf(raw.get("id"));c.order=number(raw.get("order"),set.entries.size());c.enabled=bool(raw.get("enabled"),true);c.inverted=bool(raw.get("inverted"),false);c.failureMessage=raw.get("failure-message")==null?"":String.valueOf(raw.get("failure-message"));set.entries.add(c);}catch(Exception ignored){}}
 private static int number(Object value,int fallback){try{return Integer.parseInt(String.valueOf(value));}catch(Exception ex){return fallback;}} private static boolean bool(Object value,boolean fallback){return value==null?fallback:Boolean.parseBoolean(String.valueOf(value));} private static int clamp(int value,int min,int max){return Math.max(min,Math.min(max,value));}
 private static void replace(File source,File destination)throws IOException{if(destination.exists()&&!destination.delete())throw new IOException("could not replace existing menu");if(!source.renameTo(destination))throw new IOException("could not rename temporary menu");}
 boolean delete(String id){File file=new File(dir,id+".yml");return !file.exists()||file.delete();}
}