package net.zartra.gui;
import org.bukkit.*;import org.bukkit.command.*;import org.bukkit.entity.Player;import java.io.*;import java.util.*;
final class ZGuiCommand implements CommandExecutor,TabCompleter {
 private final ZartraGUIPlugin plugin;private final MenuManager menus;private final GuiService gui;
 ZGuiCommand(ZartraGUIPlugin p,MenuManager m,GuiService g){plugin=p;menus=m;gui=g;}
 private boolean ok(CommandSender s,String n){return s.hasPermission("zartragui.admin")||s.hasPermission("zartragui."+n);}
 private boolean no(CommandSender s){s.sendMessage(Chat.c("&cYou do not have permission."));return true;}
 private boolean usage(CommandSender s){s.sendMessage(Chat.c("&eUsage: /zgui <create|edit|open|preview|duplicate|delete|list|search|export|import|save|reload|debug|version|help>"));return true;}
 private boolean menuUsage(CommandSender s,String sub){s.sendMessage(Chat.c("&eUsage: /zgui "+sub+" <menu-id>"));return true;}
 private MenuDefinition requiredMenu(CommandSender s,String sub,String[] a){if(a.length<2){menuUsage(s,sub);return null;}MenuDefinition d=menus.get(a[1]);if(d==null)s.sendMessage(Chat.c("&cUnknown menu: &f"+a[1]));return d;}
 private boolean playerOnly(CommandSender s){if(s instanceof Player)return true;s.sendMessage(Chat.c("&cThis command must be used by a player."));return false;}
 public boolean onCommand(CommandSender s,Command c,String l,String[] a){
  if(a.length==0){if(!playerOnly(s))return true;gui.main((Player)s);return true;}String sub=a[0].toLowerCase(Locale.ENGLISH);
  if("help".equals(sub))return usage(s);if("version".equals(sub)){s.sendMessage("ZartraGUI 1.1.0");return true;}if("debug".equals(sub)){if(!ok(s,"debug"))return no(s);s.sendMessage("menus="+menus.all().size());return true;}
  if("list".equals(sub)||"search".equals(sub)){String q=a.length>1?a[1].toLowerCase(Locale.ENGLISH):"";for(MenuDefinition d:menus.all())if(d.id.contains(q)||d.title.toLowerCase(Locale.ENGLISH).contains(q))s.sendMessage(d.id+" - "+d.title);return true;}
  if("reload".equals(sub)){if(!ok(s,"reload"))return no(s);plugin.reloadConfig();menus.reload();plugin.refreshAliases();plugin.inputs().clear();s.sendMessage(Chat.c("&aReloaded."));if(s instanceof Player)gui.main((Player)s);return true;}
  if("save".equals(sub)){if(!ok(s,"edit"))return no(s);try{menus.saveAll();s.sendMessage(Chat.c("&aSaved."));}catch(IOException e){s.sendMessage(Chat.c("&cSave failed."));}return true;}
  if("create".equals(sub)){if(!ok(s,"create"))return no(s);if(a.length<2){if(!playerOnly(s))return true;plugin.askCreate((Player)s);return true;}return create(s,a[1]);}
  if("open".equals(sub)){if(!ok(s,"open"))return no(s);MenuDefinition d=requiredMenu(s,sub,a);if(d==null)return true;if(!playerOnly(s))return true;menus.open((Player)s,d);return true;}
  if("preview".equals(sub)){if(!ok(s,"preview")&&!ok(s,"open"))return no(s);MenuDefinition d=requiredMenu(s,sub,a);if(d==null)return true;if(!playerOnly(s))return true;menus.openPreview((Player)s,d);return true;}
  if("import".equals(sub)){if(!ok(s,"import"))return no(s);if(a.length<2||!a[1].matches("[a-z0-9_-]{1,32}\\.yml")){s.sendMessage(Chat.c("&cInvalid import filename."));return true;}try{File from=new File(new File(plugin.getDataFolder(),"exports"),a[1]);File to=new File(new File(plugin.getDataFolder(),"menus"),a[1]);if(!from.isFile()||to.exists()){s.sendMessage(Chat.c("&cImport file missing or target already exists."));return true;}java.nio.file.Files.copy(from.toPath(),to.toPath());menus.reload();s.sendMessage(Chat.c("&aImported "+a[1]));}catch(Exception ex){s.sendMessage(Chat.c("&cImport failed."));}return true;}
  MenuDefinition d=requiredMenu(s,sub,a);if(d==null)return true;
  if("edit".equals(sub)){if(!ok(s,"edit"))return no(s);if(playerOnly(s))gui.menuSettings((Player)s,d);return true;}if("duplicate".equals(sub)){if(!ok(s,"duplicate"))return no(s);if(a.length<3||!MenuManager.validId(a[2])||menus.get(a[2])!=null){s.sendMessage(Chat.c("&cInvalid new ID."));return true;}try{menus.save(menus.duplicate(d,a[2]));plugin.refreshAliases();s.sendMessage(Chat.c("&aDuplicated."));}catch(IOException e){s.sendMessage(Chat.c("&cSave failed."));}return true;}if("delete".equals(sub)){if(!ok(s,"delete"))return no(s);menus.delete(d.id);plugin.refreshAliases();s.sendMessage(Chat.c("&aDeleted."));return true;}if("export".equals(sub)){if(!ok(s,"export"))return no(s);try{File from=new File(new File(plugin.getDataFolder(),"menus"),d.id+".yml"),dir=new File(plugin.getDataFolder(),"exports");if(!dir.exists())dir.mkdirs();File to=new File(dir,d.id+".yml");java.nio.file.Files.copy(from.toPath(),to.toPath(),java.nio.file.StandardCopyOption.REPLACE_EXISTING);s.sendMessage(Chat.c("&aExported "+to.getName()));}catch(Exception ex){s.sendMessage(Chat.c("&cExport failed."));}return true;}return usage(s);
 }
 boolean internalPicker(CommandSender s,String[] a){if(!(s instanceof Player)){s.sendMessage(Chat.c("&cThis command must be used by a player."));return true;}if(a.length!=2){s.sendMessage(Chat.c("&cPicker Expired."));return true;}return plugin.colorPicker().handle((Player)s,a[0],a[1]);}
 boolean create(CommandSender s,String id){id=id.toLowerCase(Locale.ENGLISH);if(!MenuManager.validId(id)||menus.get(id)!=null){s.sendMessage(Chat.c("&cInvalid or existing ID."));return true;}try{MenuDefinition created=menus.create(id);menus.save(created);s.sendMessage(Chat.c("&aCreated "+id));if(s instanceof Player)gui.openMenuConfiguration((Player)s,created,1);}catch(IOException e){s.sendMessage(Chat.c("&cSave failed."));}return true;}
 public List<String> onTabComplete(CommandSender s,Command c,String l,String[] a){if(a.length==1)return match(Arrays.asList("create","edit","open","preview","duplicate","delete","list","search","export","import","save","reload","debug","version","help"),a[0]);if(a.length==2&&Arrays.asList("edit","open","preview","duplicate","delete","export").contains(a[0].toLowerCase(Locale.ENGLISH))){List<String>x=new ArrayList<String>();for(MenuDefinition d:menus.all())x.add(d.id);return match(x,a[1]);}return Collections.emptyList();}
 private List<String> match(List<String>x,String q){List<String>o=new ArrayList<String>();for(String s:x)if(s.startsWith(q.toLowerCase(Locale.ENGLISH)))o.add(s);return o;}
}