package net.zartra.gui;
import org.bukkit.*;import org.bukkit.entity.Player;import org.bukkit.inventory.*;import java.io.IOException;import java.util.*;
public final class GuiEditor {private final ZartraGUIPlugin plugin;private final MenuManager manager;public GuiEditor(ZartraGUIPlugin p,MenuManager m){plugin=p;manager=m;}
 public void main(Player p){Inventory i=Bukkit.createInventory(null,27,Chat.color("&bZartraGUI"));i.setItem(11,MenuItemDefinition.named(Material.CHEST,Chat.color("&aMenus")));i.setItem(15,MenuItemDefinition.named(Material.EMERALD,Chat.color("&aCreate menu")));p.openInventory(i);}
 public void list(Player p){Inventory i=Bukkit.createInventory(null,54,Chat.color("&bMenus"));int s=0;for(MenuDefinition d:manager.all()){if(s>=45)break;i.setItem(s++,MenuItemDefinition.named(Material.CHEST,Chat.color("&e"+d.id()+" &7("+d.title()+")")));}i.setItem(49,MenuItemDefinition.named(Material.ARROW,Chat.color("&7Back")));p.openInventory(i);}
 public void editor(Player p,MenuDefinition d){Inventory i=Bukkit.createInventory(new MenuManager.MenuHolder(d.id(),true),d.rows()*9,Chat.color("&cEditing: "+d.id()));for(Map.Entry<Integer,MenuItemDefinition> e:d.items().entrySet())i.setItem(e.getKey(),e.getValue().item());p.openInventory(i);p.sendMessage(Chat.color("&ePlace items normally. Click an existing item to configure its action; close to save."));}
 public void saveEditor(Inventory inv){if(!(inv.getHolder() instanceof MenuManager.MenuHolder))return;MenuManager.MenuHolder h=(MenuManager.MenuHolder)inv.getHolder();if(!h.editor())return;MenuDefinition d=manager.get(h.id());if(d==null)return;d.items().clear();for(int x=0;x<inv.getSize();x++){ItemStack it=inv.getItem(x);if(it!=null&&it.getType()!=Material.AIR){MenuItemDefinition old=d.items().get(x);d.items().put(x,new MenuItemDefinition(it,old==null?null:old.action()));}}try{manager.save(d);}catch(IOException e){plugin.getLogger().warning("Unable to save menu "+d.id()+": "+e.getMessage());}}
 public void configure(Player p,MenuDefinition d,int slot){MenuItemDefinition item=d.items().get(slot);if(item==null)return;plugin.inputs().begin(p,new ChatInputManager.Callback(){public void accept(Player who,String raw){MenuAction a=MenuAction.parse(raw);if(a==null){who.sendMessage(Chat.color("&cInvalid action. Use PLAYER_COMMAND, CONSOLE_COMMAND, MESSAGE, OPEN_MENU, or CLOSE."));return;}item.action(a);try{manager.save(d);who.sendMessage(Chat.color("&aAction saved."));}catch(IOException e){who.sendMessage(Chat.color("&cSave failed."));}}});p.sendMessage(Chat.color("&eEnter action, e.g. &fMESSAGE: &aHello %player%"));}
}
