package net.zartra.gui;
import org.bukkit.entity.Player;import org.bukkit.event.*;import org.bukkit.event.inventory.*;import org.bukkit.event.player.*;import org.bukkit.inventory.*;
public final class GuiListener implements Listener {private final ZartraGUIPlugin plugin;private final MenuManager menus;private final GuiEditor editor;public GuiListener(ZartraGUIPlugin p,MenuManager m,GuiEditor e){plugin=p;menus=m;editor=e;}
 @EventHandler public void click(InventoryClickEvent e){if(!(e.getWhoClicked() instanceof Player))return;Inventory top=e.getView().getTopInventory();Object holder=top.getHolder();if(!(holder instanceof MenuManager.MenuHolder))return;MenuManager.MenuHolder h=(MenuManager.MenuHolder)holder;Player p=(Player)e.getWhoClicked();if(e.getRawSlot()>=top.getSize()){if(h.editor()&&(e.isShiftClick()||e.getClick()==ClickType.NUMBER_KEY||e.getClick()==ClickType.DOUBLE_CLICK))e.setCancelled(true);return;}if(!h.editor()){e.setCancelled(true);MenuDefinition d=menus.get(h.id());if(d!=null)menus.action(p,d,d.items().get(e.getRawSlot())==null?null:d.items().get(e.getRawSlot()).action());return;}if(e.isShiftClick()||e.getClick()==ClickType.NUMBER_KEY||e.getClick()==ClickType.DOUBLE_CLICK){e.setCancelled(true);return;}if(e.getClick()==ClickType.RIGHT&&e.getCurrentItem()!=null){e.setCancelled(true);MenuDefinition d=menus.get(h.id());if(d!=null)editor.configure(p,d,e.getRawSlot());}}
 @EventHandler public void drag(InventoryDragEvent e){Object h=e.getView().getTopInventory().getHolder();if(h instanceof MenuManager.MenuHolder){for(int slot:e.getRawSlots())if(slot<e.getView().getTopInventory().getSize()){e.setCancelled(true);return;}}}
 @EventHandler public void close(InventoryCloseEvent e){editor.saveEditor(e.getInventory());}
 @EventHandler(priority=EventPriority.LOWEST) public void chat(AsyncPlayerChatEvent e){if(plugin.inputs().handle(e.getPlayer(),e.getMessage()))e.setCancelled(true);}
 @EventHandler public void quit(PlayerQuitEvent e){plugin.inputs().remove(e.getPlayer());}
}
